window.RADICALS = [
    {id: 1, char: "一", meaning: "один", pinyin: "yī", variants: ["⼀"]},
    {id: 2, char: "丨", meaning: "линия", pinyin: "gǔn", variants: ["⼁"]},
    {id: 3, char: "丶", meaning: "точка", pinyin: "zhǔ", variants: ["⼂"]},
    {id: 4, char: "丿", meaning: "черта влево", pinyin: "piě", variants: ["⼃"]},
    {id: 5, char: "乙", meaning: "второй", pinyin: "yǐ", variants: ["⼄"]},
    {id: 6, char: "亅", meaning: "крюк", pinyin: "jué", variants: ["⼅"]},
    {id: 7, char: "二", meaning: "два", pinyin: "èr", variants: ["⼆"]},
    {id: 8, char: "亠", meaning: "крышка", pinyin: "tóu", variants: ["⼇"]},
    {id: 9, char: "人", meaning: "человек", pinyin: "rén", variants: ["⼈", "⺅", "𠆢"]},
    {id: 10, char: "儿", meaning: "ноги", pinyin: "ér", variants: ["⼉"]},
    {id: 11, char: "入", meaning: "входить", pinyin: "rù", variants: ["⼊"]},
    {id: 12, char: "八", meaning: "восемь", pinyin: "bā", variants: ["⼋", "丷"]},
    {id: 13, char: "冂", meaning: "открытость", pinyin: "jiōng", variants: ["⼌"]},
    {id: 14, char: "冖", meaning: "крышка", pinyin: "mì", variants: ["⼍"]},
    {id: 15, char: "冫", meaning: "лёд", pinyin: "bīng", variants: ["⼎"]},
    {id: 16, char: "几", meaning: "столик", pinyin: "jī", variants: ["⼏"]},
    {id: 17, char: "凵", meaning: "открытый рот", pinyin: "kǎn", variants: ["⼐"]},
    {id: 18, char: "刀", meaning: "нож", pinyin: "dāo", variants: ["⼑", "⺈", "刂"]},
    {id: 19, char: "力", meaning: "сила", pinyin: "lì", variants: ["⼒"]},
    {id: 20, char: "勹", meaning: "обёртывать", pinyin: "bāo", variants: ["⼓"]},
    {id: 21, char: "匕", meaning: "ложка", pinyin: "bǐ", variants: ["⼔"]},
    {id: 22, char: "匚", meaning: "коробка", pinyin: "fāng", variants: ["⼕"]},
    {id: 23, char: "匸", meaning: "прятаться", pinyin: "xǐ", variants: ["⼖"]},
    {id: 24, char: "十", meaning: "десять", pinyin: "shí", variants: ["⼗"]},
    {id: 25, char: "卜", meaning: "гадать", pinyin: "bǔ", variants: ["⼘", "⺊"]},
    {id: 26, char: "卩", meaning: "печать", pinyin: "jié", variants: ["⼙", "㔾"]},
    {id: 27, char: "厂", meaning: "утес", pinyin: "hǎn", variants: ["⼚"]},
    {id: 28, char: "厶", meaning: "частный", pinyin: "sī", variants: ["⼛"]},
    {id: 29, char: "又", meaning: "снова", pinyin: "yòu", variants: ["⼜"]},
    {id: 30, char: "口", meaning: "рот", pinyin: "kǒu", variants: ["⼝"]},
    {id: 31, char: "囗", meaning: "ограда", pinyin: "wéi", variants: ["⼞"]},
    {id: 32, char: "土", meaning: "земля", pinyin: "tǔ", variants: ["⼟"]},
    {id: 33, char: "士", meaning: "учёный", pinyin: "shì", variants: ["⼠"]},
    {id: 34, char: "夂", meaning: "идти медленно", pinyin: "zhǐ", variants: ["⼡"]},
    {id: 35, char: "夊", meaning: "идти", pinyin: "suī", variants: ["⼢"]},
    {id: 36, char: "夕", meaning: "вечер", pinyin: "xī", variants: ["⼣"]},
    {id: 37, char: "大", meaning: "большой", pinyin: "dà", variants: ["⼤"]},
    {id: 38, char: "女", meaning: "женщина", pinyin: "nǚ", variants: ["⼥", "⺦"]},
    {id: 39, char: "子", meaning: "ребёнок", pinyin: "zǐ", variants: ["⼦"]},
    {id: 40, char: "宀", meaning: "крыша", pinyin: "mián", variants: ["⼧"]},
    {id: 41, char: "寸", meaning: "дюйм", pinyin: "cùn", variants: ["⼨"]},
    {id: 42, char: "小", meaning: "маленький", pinyin: "xiǎo", variants: ["⼩", "⺌"]},
    {id: 43, char: "尢", meaning: "хромой", pinyin: "wāng", variants: ["⼪"]},
    {id: 44, char: "尸", meaning: "труп", pinyin: "shī", variants: ["⼫"]},
    {id: 45, char: "屮", meaning: "росток", pinyin: "chè", variants: ["⼬"]},
    {id: 46, char: "山", meaning: "гора", pinyin: "shān", variants: ["⼭"]},
    {id: 47, char: "巛", meaning: "река", pinyin: "chuān", variants: ["⼮"]},
    {id: 48, char: "工", meaning: "работа", pinyin: "gōng", variants: ["⼯"]},
    {id: 49, char: "己", meaning: "сам", pinyin: "jǐ", variants: ["⼰"]},
    {id: 50, char: "巾", meaning: "полотенце", pinyin: "jīn", variants: ["⼱"]},
    {id: 51, char: "干", meaning: "щит", pinyin: "gān", variants: ["⼲"]},
    {id: 52, char: "幺", meaning: "мелкий", pinyin: "yāo", variants: ["⼳"]},
    {id: 53, char: "广", meaning: "навес", pinyin: "guǎng", variants: ["⼴"]},
    {id: 54, char: "廴", meaning: "идти", pinyin: "yǐn", variants: ["⼵"]},
    {id: 55, char: "廾", meaning: "две руки", pinyin: "gǒng", variants: ["⼶"]},
    {id: 56, char: "弋", meaning: "стрелять", pinyin: "yì", variants: ["⼷"]},
    {id: 57, char: "弓", meaning: "лук", pinyin: "gōng", variants: ["⼸"]},
    {id: 58, char: "彐", meaning: "свинья", pinyin: "jì", variants: ["⼹", "⺕"]},
    {id: 59, char: "彡", meaning: "щетина", pinyin: "shān", variants: ["⼺"]},
    {id: 60, char: "彳", meaning: "шаг", pinyin: "chì", variants: ["⼻"]},
    {id: 61, char: "心", meaning: "сердце", pinyin: "xīn", variants: ["⼼", "⺗", "忄"]},
    {id: 62, char: "戈", meaning: "алебарда", pinyin: "gē", variants: ["⼽"]},
    {id: 63, char: "戶", meaning: "дверь", pinyin: "hù", variants: ["⼾", "户"]},
    {id: 64, char: "手", meaning: "рука", pinyin: "shǒu", variants: ["⼿", "扌"]},
    {id: 65, char: "支", meaning: "ветвь", pinyin: "zhī", variants: ["⽀"]},
    {id: 66, char: "攴", meaning: "бить", pinyin: "pū", variants: ["⽁", "攵"]},
    {id: 67, char: "文", meaning: "письмо", pinyin: "wén", variants: ["⽂"]},
    {id: 68, char: "斗", meaning: "ковш", pinyin: "dǒu", variants: ["⽃"]},
    {id: 69, char: "斤", meaning: "топор", pinyin: "jīn", variants: ["⽄"]},
    {id: 70, char: "方", meaning: "квадрат", pinyin: "fāng", variants: ["⽅"]},
    {id: 71, char: "无", meaning: "нет", pinyin: "wú", variants: ["⽆"]},
    {id: 72, char: "日", meaning: "солнце", pinyin: "rì", variants: ["⽇"]},
    {id: 73, char: "曰", meaning: "говорить", pinyin: "yuē", variants: ["⽈"]},
    {id: 74, char: "月", meaning: "луна", pinyin: "yuè", variants: ["⽉"]},
    {id: 75, char: "木", meaning: "дерево", pinyin: "mù", variants: ["⽊"]},
    {id: 76, char: "欠", meaning: "зевать", pinyin: "qiàn", variants: ["⽋"]},
    {id: 77, char: "止", meaning: "остановиться", pinyin: "zhǐ", variants: ["⽌"]},
    {id: 78, char: "歹", meaning: "смерть", pinyin: "dǎi", variants: ["⽍"]},
    {id: 79, char: "殳", meaning: "копьё", pinyin: "shū", variants: ["⽎"]},
    {id: 80, char: "毋", meaning: "не", pinyin: "wú", variants: ["⽏"]},
    {id: 81, char: "比", meaning: "сравнивать", pinyin: "bǐ", variants: ["⽐"]},
    {id: 82, char: "毛", meaning: "шерсть", pinyin: "máo", variants: ["⽑"]},
    {id: 83, char: "氏", meaning: "фамилия", pinyin: "shì", variants: ["⽒"]},
    {id: 84, char: "气", meaning: "пар", pinyin: "qì", variants: ["⽓"]},
    {id: 85, char: "水", meaning: "вода", pinyin: "shuǐ", variants: ["⽔", "氵"]},
    {id: 86, char: "火", meaning: "огонь", pinyin: "huǒ", variants: ["⽕", "灬"]},
    {id: 87, char: "爪", meaning: "коготь", pinyin: "zhǎo", variants: ["⽖", "爫"]},
    {id: 88, char: "父", meaning: "отец", pinyin: "fù", variants: ["⽗"]},
    {id: 89, char: "爻", meaning: "гадание", pinyin: "yáo", variants: ["⽘"]},
    {id: 90, char: "爿", meaning: "доска", pinyin: "pán", variants: ["⽙"]},
    {id: 91, char: "片", meaning: "пластина", pinyin: "piàn", variants: ["⽚"]},
    {id: 92, char: "牙", meaning: "зуб", pinyin: "yá", variants: ["⽛"]},
    {id: 93, char: "牛", meaning: "корова", pinyin: "niú", variants: ["⽜", "⺧"]},
    {id: 94, char: "犬", meaning: "собака", pinyin: "quǎn", variants: ["⽝", "犭"]},
    {id: 95, char: "玄", meaning: "тёмный", pinyin: "xuán", variants: ["⽞"]},
    {id: 96, char: "玉", meaning: "нефрит", pinyin: "yù", variants: ["⽟", "⺩"]},
    {id: 97, char: "瓜", meaning: "тыква", pinyin: "guā", variants: ["⽠"]},
    {id: 98, char: "瓦", meaning: "черепица", pinyin: "wǎ", variants: ["⽡"]},
    {id: 99, char: "甘", meaning: "сладкий", pinyin: "gān", variants: ["⽢"]},
    {id: 100, char: "生", meaning: "жизнь", pinyin: "shēng", variants: ["⽣"]},
    {id: 101, char: "用", meaning: "использовать", pinyin: "yòng", variants: ["⽤"]},
    {id: 102, char: "田", meaning: "поле", pinyin: "tián", variants: ["⽥"]},
    {id: 103, char: "疋", meaning: "рулон", pinyin: "pǐ", variants: ["⽦"]},
    {id: 104, char: "疒", meaning: "болезнь", pinyin: "nè", variants: ["⽧"]},
    {id: 105, char: "癶", meaning: "ступня", pinyin: "bō", variants: ["⽨"]},
    {id: 106, char: "白", meaning: "белый", pinyin: "bái", variants: ["⽩"]},
    {id: 107, char: "皮", meaning: "кожа", pinyin: "pí", variants: ["⽪"]},
    {id: 108, char: "皿", meaning: "посуда", pinyin: "mǐn", variants: ["⽫"]},
    {id: 109, char: "目", meaning: "глаз", pinyin: "mù", variants: ["⽬"]},
    {id: 110, char: "矛", meaning: "копьё", pinyin: "máo", variants: ["⽭"]},
    {id: 111, char: "矢", meaning: "стрела", pinyin: "shǐ", variants: ["⽮"]},
    {id: 112, char: "石", meaning: "камень", pinyin: "shí", variants: ["⽯"]},
    {id: 113, char: "示", meaning: "дух", pinyin: "shì", variants: ["⽰", "⺬"]},
    {id: 114, char: "禸", meaning: "след", pinyin: "róu", variants: ["⽱"]},
    {id: 115, char: "禾", meaning: "злак", pinyin: "hé", variants: ["⽲"]},
    {id: 116, char: "穴", meaning: "пещера", pinyin: "xué", variants: ["⽳"]},
    {id: 117, char: "立", meaning: "стоять", pinyin: "lì", variants: ["⽴"]},
    {id: 118, char: "竹", meaning: "бамбук", pinyin: "zhú", variants: ["⽵", "⺮"]},
    {id: 119, char: "米", meaning: "рис", pinyin: "mǐ", variants: ["⽶"]},
    {id: 120, char: "糸", meaning: "шёлк", pinyin: "mì", variants: ["⽷", "纟"]},
    {id: 121, char: "缶", meaning: "кувшин", pinyin: "fǒu", variants: ["⽸"]},
    {id: 122, char: "网", meaning: "сеть", pinyin: "wǎng", variants: ["⽹", "罒"]},
    {id: 123, char: "羊", meaning: "овца", pinyin: "yáng", variants: ["⽺", "⺶"]},
    {id: 124, char: "羽", meaning: "перо", pinyin: "yǔ", variants: ["⽻"]},
    {id: 125, char: "老", meaning: "старый", pinyin: "lǎo", variants: ["⽼"]},
    {id: 126, char: "而", meaning: "и", pinyin: "ér", variants: ["⽽"]},
    {id: 127, char: "耒", meaning: "плуг", pinyin: "lěi", variants: ["⽾"]},
    {id: 128, char: "耳", meaning: "ухо", pinyin: "ěr", variants: ["⽿"]},
    {id: 129, char: "聿", meaning: "кисть", pinyin: "yù", variants: ["⾀"]},
    {id: 130, char: "肉", meaning: "мясо", pinyin: "ròu", variants: ["⾁", "⺼"]},
    {id: 131, char: "臣", meaning: "министр", pinyin: "chén", variants: ["⾂"]},
    {id: 132, char: "自", meaning: "сам", pinyin: "zì", variants: ["⾃"]},
    {id: 133, char: "至", meaning: "достигать", pinyin: "zhì", variants: ["⾄"]},
    {id: 134, char: "臼", meaning: "ступа", pinyin: "jiù", variants: ["⾅"]},
    {id: 135, char: "舌", meaning: "язык", pinyin: "shé", variants: ["⾆"]},
    {id: 136, char: "舛", meaning: "ошибка", pinyin: "chuǎn", variants: ["⾇"]},
    {id: 137, char: "舟", meaning: "лодка", pinyin: "zhōu", variants: ["⾈"]},
    {id: 138, char: "艮", meaning: "остановка", pinyin: "gèn", variants: ["⾉"]},
    {id: 139, char: "色", meaning: "цвет", pinyin: "sè", variants: ["⾊"]},
    {id: 140, char: "艸", meaning: "трава", pinyin: "cǎo", variants: ["⾋", "艹"]},
    {id: 141, char: "虍", meaning: "тигр", pinyin: "hū", variants: ["⾌"]},
    {id: 142, char: "虫", meaning: "насекомое", pinyin: "chóng", variants: ["⾍"]},
    {id: 143, char: "血", meaning: "кровь", pinyin: "xuè", variants: ["⾎"]},
    {id: 144, char: "行", meaning: "идти", pinyin: "xíng", variants: ["⾏"]},
    {id: 145, char: "衣", meaning: "одежда", pinyin: "yī", variants: ["⾐", "衤"]},
    {id: 146, char: "襾", meaning: "покрывать", pinyin: "yà", variants: ["⾑"]},
    {id: 147, char: "見", meaning: "видеть", pinyin: "jiàn", variants: ["⾒"]},
    {id: 148, char: "角", meaning: "рог", pinyin: "jiǎo", variants: ["⾓"]},
    {id: 149, char: "言", meaning: "речь", pinyin: "yán", variants: ["⾔", "讠"]},
    {id: 150, char: "谷", meaning: "долина", pinyin: "gǔ", variants: ["⾕"]},
    {id: 151, char: "豆", meaning: "боб", pinyin: "dòu", variants: ["⾖"]},
    {id: 152, char: "豕", meaning: "свинья", pinyin: "shǐ", variants: ["⾗"]},
    {id: 153, char: "豸", meaning: "барс", pinyin: "zhì", variants: ["⾘"]},
    {id: 154, char: "貝", meaning: "ракушка", pinyin: "bèi", variants: ["⾙", "贝"]},
    {id: 155, char: "赤", meaning: "красный", pinyin: "chì", variants: ["⾚"]},
    {id: 156, char: "走", meaning: "бежать", pinyin: "zǒu", variants: ["⾛"]},
    {id: 157, char: "足", meaning: "нога", pinyin: "zú", variants: ["⾜", "⻊"]},
    {id: 158, char: "身", meaning: "тело", pinyin: "shēn", variants: ["⾝"]},
    {id: 159, char: "車", meaning: "повозка", pinyin: "chē", variants: ["⾞", "车"]},
    {id: 160, char: "辛", meaning: "острый", pinyin: "xīn", variants: ["⾟"]},
    {id: 161, char: "辰", meaning: "утро", pinyin: "chén", variants: ["⾠"]},
    {id: 162, char: "辵", meaning: "идти", pinyin: "chuò", variants: ["⾡", "辶"]},
    {id: 163, char: "邑", meaning: "город", pinyin: "yì", variants: ["⾢", "阝"]},
    {id: 164, char: "酉", meaning: "вино", pinyin: "yǒu", variants: ["⾣"]},
    {id: 165, char: "釆", meaning: "различать", pinyin: "biàn", variants: ["⾤"]},
    {id: 166, char: "里", meaning: "деревня", pinyin: "lǐ", variants: ["⾥"]},
    {id: 167, char: "金", meaning: "золото", pinyin: "jīn", variants: ["⾦", "钅"]},
    {id: 168, char: "長", meaning: "длинный", pinyin: "cháng", variants: ["⾧", "长"]},
    {id: 169, char: "門", meaning: "ворота", pinyin: "mén", variants: ["⾨", "门"]},
    {id: 170, char: "阜", meaning: "холм", pinyin: "fù", variants: ["⾩", "阝"]},
    {id: 171, char: "隶", meaning: "раб", pinyin: "lì", variants: ["⾪"]},
    {id: 172, char: "隹", meaning: "птица", pinyin: "zhuī", variants: ["⾫"]},
    {id: 173, char: "雨", meaning: "дождь", pinyin: "yǔ", variants: ["⾬"]},
    {id: 174, char: "靑", meaning: "синий", pinyin: "qīng", variants: ["⾭"]},
    {id: 175, char: "非", meaning: "не", pinyin: "fēi", variants: ["⾮"]},
    {id: 176, char: "面", meaning: "лицо", pinyin: "miàn", variants: ["⾯"]},
    {id: 177, char: "革", meaning: "кожа", pinyin: "gé", variants: ["⾰"]},
    {id: 178, char: "韋", meaning: "дублёная кожа", pinyin: "wéi", variants: ["⾱", "韦"]},
    {id: 179, char: "韭", meaning: "лук-порей", pinyin: "jiǔ", variants: ["⾲"]},
    {id: 180, char: "音", meaning: "звук", pinyin: "yīn", variants: ["⾳"]},
    {id: 181, char: "頁", meaning: "страница", pinyin: "yè", variants: ["⾴", "页"]},
    {id: 182, char: "風", meaning: "ветер", pinyin: "fēng", variants: ["⾵", "风"]},
    {id: 183, char: "飛", meaning: "летать", pinyin: "fēi", variants: ["⾶", "飞"]},
    {id: 184, char: "食", meaning: "еда", pinyin: "shí", variants: ["⾷", "饣"]},
    {id: 185, char: "首", meaning: "голова", pinyin: "shǒu", variants: ["⾸"]},
    {id: 186, char: "香", meaning: "аромат", pinyin: "xiāng", variants: ["⾹"]},
    {id: 187, char: "馬", meaning: "лошадь", pinyin: "mǎ", variants: ["⾺", "马"]},
    {id: 188, char: "骨", meaning: "кость", pinyin: "gǔ", variants: ["⾻"]},
    {id: 189, char: "高", meaning: "высокий", pinyin: "gāo", variants: ["⾼"]},
    {id: 190, char: "髟", meaning: "волосы", pinyin: "biāo", variants: ["⾽"]},
    {id: 191, char: "鬥", meaning: "драка", pinyin: "dòu", variants: ["⾾"]},
    {id: 192, char: "鬯", meaning: "жертвенное вино", pinyin: "chàng", variants: ["⾿"]},
    {id: 193, char: "鬲", meaning: "треножник", pinyin: "lì", variants: ["⿀"]},
    {id: 194, char: "鬼", meaning: "призрак", pinyin: "guǐ", variants: ["⿁"]},
    {id: 195, char: "魚", meaning: "рыба", pinyin: "yú", variants: ["⿂", "鱼"]},
    {id: 196, char: "鳥", meaning: "птица", pinyin: "niǎo", variants: ["⿃", "鸟"]},
    {id: 197, char: "鹵", meaning: "солончак", pinyin: "lù", variants: ["⿄"]},
    {id: 198, char: "鹿", meaning: "олень", pinyin: "lù", variants: ["⿅"]},
    {id: 199, char: "麥", meaning: "пшеница", pinyin: "mài", variants: ["⿆", "麦"]},
    {id: 200, char: "麻", meaning: "конопля", pinyin: "má", variants: ["⿇"]},
    {id: 201, char: "黃", meaning: "жёлтый", pinyin: "huáng", variants: ["⿈", "黄"]},
    {id: 202, char: "黍", meaning: "просо", pinyin: "shǔ", variants: ["⿉"]},
    {id: 203, char: "黑", meaning: "чёрный", pinyin: "hēi", variants: ["⿊"]},
    {id: 204, char: "黹", meaning: "вышивать", pinyin: "zhǐ", variants: ["⿋"]},
    {id: 205, char: "黽", meaning: "лягушка", pinyin: "mǐn", variants: ["⿌"]},
    {id: 206, char: "鼎", meaning: "треножник", pinyin: "dǐng", variants: ["⿍"]},
    {id: 207, char: "鼓", meaning: "барабан", pinyin: "gǔ", variants: ["⿎"]},
    {id: 208, char: "鼠", meaning: "мышь", pinyin: "shǔ", variants: ["⿏"]},
    {id: 209, char: "鼻", meaning: "нос", pinyin: "bí", variants: ["⿐"]},
    {id: 210, char: "齊", meaning: "ровный", pinyin: "qí", variants: ["⿑", "齐"]},
    {id: 211, char: "齒", meaning: "зуб", pinyin: "chǐ", variants: ["⿒", "齿"]},
    {id: 212, char: "龍", meaning: "дракон", pinyin: "lóng", variants: ["⿓", "龙"]},
    {id: 213, char: "龜", meaning: "черепаха", pinyin: "guī", variants: ["⿔", "龟"]},
    {id: 214, char: "龠", meaning: "флейта", pinyin: "yuè", variants: ["⿕"]}
];